services:
  - type: web
    name: my-service
    env: node
    buildCommand: "apt-get update && apt-get install -y libnss3 libxss1 libasound2 chromium-browser && npm install"
    startCommand: "npm start"
