POST http://localhost:3000/api/v1/bypass
Content-Type: application/json

{
    "formUrl":"http://url5603.blsinternational.com/ls/click?upn=u001.GaJBgDIo1Owv3jaLjoOFP6nzOLrc0O1Xeqk0-2FZWOYcjqTvOqKH8pn5CMlj6iOq-2BzoHtX24SOqhMpsMX-2F4Tbl7-2BztfODp58n52UlnuxS5ZhUu-2B3r1h27t3-2FUJTrl-2BntCVMFoKuD6lSvLnvnN6Flb7q6YR2O1JvHP3FXKR8YRYz5ZyZuA7CRI8xQy9xJLXRd-2F4AXWEhVQ53CZzmM0i6spHZwgS0pyKTH2Q-2B7tjt56ypItnlOJLZjY-2Fk1v7RFHV-2FzJsuOd61p0FkfTJFkQoebA77pxgMsmzDSi-2FEmfoA2A4nrFurAvvFHHRwv0UC-2F4YeuzAwCIDodkTeWSqlDId0AQ3thVYo372nVA4bnukWrYgQC8-3DgDzI_iokptJSioas16WNY2Yf3OzeutfxjnRh-2Fac20TsniS5MNlwm-2F-2BlooZaq3NUC79X9rdAdu8nkZyRPAlB5bTWSUjrFdfMzTmPjWTuaan0qvuNWEL81GuXMDPdi-2FoByDFRJIjxTcUHsWfoKqizKH-2FOK-2BI9AUj6cK8yMASmTxORk9st92Ks0ZmmT-2BwVH-2FlGx-2BGjHkQIyQNJBcTFEaoMnvaxmIiw-3D-3D",
    "emailToSubmit":"matarprojet@gmail.com"

}
//